//! Go module repositories the snapshot cases read.
//!
//! Every tree is written whole, including the directories a snapshot must
//! refuse to walk, so "the snapshot did not read it" is a claim about the walk
//! rather than about a directory that happened to be missing.

use crate::resolution::fixture::FixtureFile;

/// One main module whose single directory states all three package contexts,
/// plus a second package with production sources alone.
///
/// `app.go` is the shared source: the production unit and the internal-test
/// unit both instantiate it, and the snapshot must still store it once.
pub const PACKAGE_CONTEXTS: &[FixtureFile] = &[
    ("repo/go.mod", "module example.com/app\n\ngo 1.22\n"),
    (
        "repo/app.go",
        "package app\n\nfunc Run() string {\n\treturn Name()\n}\n",
    ),
    (
        "repo/app_test.go",
        "package app\n\nfunc probe() string {\n\treturn Run()\n}\n",
    ),
    (
        "repo/api_test.go",
        "package app_test\n\nimport \"example.com/app\"\n\nfunc drive() string {\n\treturn app.Run()\n}\n",
    ),
    (
        "repo/util/util.go",
        "package util\n\nfunc Name() string {\n\treturn \"util\"\n}\n",
    ),
];

/// Every reserved tree the Go command keeps out of package discovery, one
/// generated source that must stay in, one unadmitted nested module, and one
/// non-Go file.
pub const RESERVED_TREES: &[FixtureFile] = &[
    ("repo/go.mod", "module example.com/reserved\n\ngo 1.22\n"),
    ("repo/main.go", "package main\n"),
    (
        "repo/zz_generated.go",
        "// Code generated by a tool. DO NOT EDIT.\n\npackage main\n",
    ),
    ("repo/README.md", "# not go source\n"),
    ("repo/.hidden/hidden.go", "package hidden\n"),
    ("repo/_scratch/scratch.go", "package scratch\n"),
    ("repo/testdata/golden.go", "package golden\n"),
    ("repo/vendor/example.com/dep/dep.go", "package dep\n"),
    ("repo/nested/go.mod", "module example.com/nested\n"),
    ("repo/nested/nested.go", "package nested\n"),
];

/// A main module and the local replacement it requires, so a snapshot states
/// two modules, two package units, and one module edge.
pub const REPLACED_MODULE: &[FixtureFile] = &[
    (
        "repo/go.mod",
        "module example.com/root\n\ngo 1.22\n\nrequire example.com/lib v1.0.0\n\nreplace example.com/lib => ./local/lib\n",
    ),
    (
        "repo/root.go",
        "package root\n\nimport \"example.com/lib\"\n\nfunc Run() string {\n\treturn lib.Name()\n}\n",
    ),
    ("repo/local/lib/go.mod", "module example.com/lib\n"),
    (
        "repo/local/lib/lib.go",
        "package lib\n\nfunc Name() string {\n\treturn \"lib\"\n}\n",
    ),
];

/// One module whose sources carry every retained build predicate: both comment
/// spellings, an operating-system suffix, a suffix pair, the test context, and
/// the pseudo-import that states the foreign-function condition.
pub const BUILD_PREDICATES: &[FixtureFile] = &[
    ("repo/go.mod", "module example.com/build\n\ngo 1.22\n"),
    ("repo/base.go", "package build\n"),
    (
        "repo/tagged.go",
        "//go:build linux && !purego\n\npackage build\n",
    ),
    ("repo/legacy.go", "// +build darwin\n\npackage build\n"),
    ("repo/plat_windows.go", "package build\n"),
    ("repo/plat_linux_arm64.go", "package build\n"),
    (
        "repo/bridge.go",
        "package build\n\nimport \"C\"\n\nfunc bridge() {}\n",
    ),
    ("repo/base_test.go", "package build\n"),
];

/// A module whose one source states a package clause and nothing else, used as
/// the baseline every refusal row perturbs.
pub const MINIMAL: &[FixtureFile] = &[
    ("repo/go.mod", "module example.com/minimal\n\ngo 1.22\n"),
    ("repo/minimal.go", "package minimal\n"),
];
